version: '2'
services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    links:
      - mongo
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /data/mongodb/db:/data/db
